version: '3.10'

services:
  db:
    image: postgres
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cloudxlab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ajayvardhan
    ports:
      - 5432:5432
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=cloudxlab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ajayvardhan
    depends_on:
      - db